name: Run Crawler script

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

env:
  # 깃허브가 제안한 대로 Node.js 24 사용을 강제합니다.
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 최신 환경에 맞게 파이썬 버전도 살짝 높였습니다.
          
      - name: Install libraries
        run: pip install requests beautifulsoup4
        
      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python crawl.py
        
      - name: Update log
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          touch last_posts.txt
          git add last_posts.txt
          git commit -m "Update last post" || echo "No changes to commit"
          git push
